"""Forager agents - find patterns across multiple observations."""

import asyncio
import random
import time
from typing import Optional, List, Tuple
from ..core.signal_store import SignalStore, Signal, deposit_with_context
from ..llm.simple_llm import SimpleLLM
from ..core.verification import SignalVerifier
from ..core.signal_types import SignalType, INITIAL, SUPPORT, CRITIQUE
from ..core.logging_config import get_logger
from ..core.stage_coordinator import StagedAgent

logger = get_logger(__name__)


class Forager(StagedAgent):
    """Forager agent - develops and refines initial signals.

    Foragers sample existing signals (generated by scouts or other agents) and
    either elaborate on them (SUPPORT) or critique them (CRITIQUE), adding depth
    and substance to the swarm's exploration.
    """

    def __init__(self, agent_id: str, input_type: str = "INITIAL", output_type: str = "SUPPORT",
                 enable_verification: bool = True, mode: str = "creative", thesis: Optional[str] = None,
                 task_config=None):
        """Initialize forager.

        Args:
            agent_id: Unique agent ID
            input_type: Signal type to sample and develop
            output_type: Signal type to deposit (SUPPORT or CRITIQUE)
            enable_verification: Enable signal quality verification
            mode: Operating mode (creative/debate)
            thesis: Task prompt or thesis for context
            task_config: Optional TaskConfig for prompt templates (composition pattern)
        """
        self.agent_id = agent_id
        self.input_type = input_type
        self.output_type = output_type
        self.enable_verification = enable_verification
        self.mode = mode
        self.thesis = thesis
        self.task_config = task_config  # NEW: Config injection instead of monkey patching
        self.active = True
        self.actions_taken = 0

        # Quality verifier (only used if enable_verification=True)
        self.verifier = SignalVerifier(min_quality_score=0.4) if enable_verification else None

    async def run(self, signal_store: SignalStore, llm: SimpleLLM,
                  max_actions: int = None):
        """Run forager behavior loop - develop input signals into output signals.

        Args:
            signal_store: Shared signal store
            llm: Language model
            max_actions: Optional maximum actions (None = run until stopped)
        """
        # Event-driven: wait for and process input signals
        if self.actions_taken == 0:
            logger.info(f"{self.agent_id} event-driven: {self.input_type} → {self.output_type}")

        while self.active and (max_actions is None or self.actions_taken < max_actions):
            # PURE EVENT-DRIVEN: Check if signals exist, if not, wait for event
            if not signal_store.has_signals(self.input_type):
                # Wait for signal event with short timeout for responsiveness
                await signal_store.wait_for_signal(self.input_type, timeout=1.0)
                signal_store.clear_signal_event(self.input_type)
                continue

            # Signals exist - process them
            await self.run_creative(signal_store, llm)
            self.actions_taken += 1
            # No sleep - pure stigmergic event-driven behavior

    async def run_creative(self, signal_store: SignalStore, llm: SimpleLLM):
        """Run creative mode: sample input signals and generate output signals.

        Args:
            signal_store: Signal store
            llm: Language model
        """
        # Get input type (with defensive check)
        input_type = getattr(self, 'input_type', None)
        if not input_type:
            return  # Fail silently, retry on next iteration

        # Sample a signal of the input type (e.g., "DRAFT")
        input_signals = signal_store.sample_weighted(input_type, n=1)

        if not input_signals:
            # No signals to process - just return, will retry
            return

        signal = input_signals[0]

        # Generate prompt using monkey-patched _make_prompt
        if hasattr(self, '_make_prompt'):
            prompt = self._make_prompt(signal)
        else:
            # Fallback if no custom prompt
            prompt = f"Task: {self.thesis}\n\nParent signal: {signal.content}\n\nGenerate {self.output_type}:"

        # Generate content
        # Read max_tokens from intake profile if available, otherwise use quality default
        max_tokens = 220  # High-quality default (was 100)
        if self.task_config and hasattr(self.task_config, 'intake_profile'):
            max_tokens = self.task_config.intake_profile.forager_tokens

        try:
            content = await llm.generate(prompt, max_tokens=max_tokens, temperature=0.7)

            if not content:
                logger.debug(f"{self.agent_id} LLM returned None/empty content")
                return

            if len(content.strip()) <= 20:
                logger.debug(f"{self.agent_id} content too short: {len(content.strip())} chars (need >20)")
                return

            # Deposit new signal of output type
            signal_id = signal_store.deposit(
                signal_type=self.output_type,
                content=content.strip(),
                strength=0.6,
                depositor=self.agent_id,
                parent=signal.id
            )

            logger.info(f"{self.agent_id} deposited {signal_id} (strength=0.60)")
        except Exception as e:
            logger.error(f"{self.agent_id} generation error: {e}", exc_info=True)

    async def develop(self, signal: Signal, llm: SimpleLLM) -> Optional[str]:
        """Develop a signal's idea further.

        Args:
            signal: Signal to develop
            llm: Language model

        Returns:
            Developed content or None
        """
        prompt = self._make_prompt(signal)

        # Use per-agent temperature from config
        from ..core.config import TEMP_FORAGER

        # Read max_tokens from intake profile if available
        max_tokens = 220  # High-quality default
        if self.task_config and hasattr(self.task_config, 'intake_profile'):
            max_tokens = self.task_config.intake_profile.forager_tokens

        try:
            result = await llm.generate(prompt, max_tokens=max_tokens, temperature=TEMP_FORAGER)
            if result and len(result.strip()) > 15:
                return result.strip()
        except Exception as e:
            logger.error(f"{self.agent_id} development error: {e}", exc_info=True)

        return None

    def assess_strength(self, content: str) -> float:
        """Assess developed content strength — dispatches on TaskFrame.strength_mode."""
        frame = getattr(self.task_config, 'task_frame', None) if self.task_config else None
        if frame and getattr(frame, 'strength_mode', 'prose') == 'code':
            return self._assess_strength_code(content)
        return self._assess_strength_prose(content)

    def _assess_strength_code(self, text: str) -> float:
        """Score code signals by structural indicators."""
        import random as _random
        score = 0.45
        score += 0.20 if ('def ' in text or 'class ' in text) else 0.0
        score += 0.10 if ('return ' in text or 'yield ' in text) else 0.0
        score += 0.08 if '```' in text else 0.0
        score += 0.05 if ('import ' in text[:150]) else 0.0
        score += min(0.12, len(text) / 500.0)
        score += _random.uniform(-0.03, 0.03)
        return max(0.0, min(1.0, score))

    def _assess_strength_prose(self, content: str) -> float:
        """Original prose strength heuristics."""
        length = len(content)
        has_numbers = any(c.isdigit() for c in content)
        has_specifics = any(word in content.lower() for word in
                           ['because', 'therefore', 'study', 'data', 'research',
                            'however', 'although', 'evidence', 'shows', 'indicates',
                            'demonstrates', 'according to', 'suggests'])
        has_references = any(word in content.lower() for word in
                            ['ipcc', 'nasa', 'report', 'journal', 'analysis',
                             'university', 'research', 'published'])
        has_reasoning = any(word in content.lower() for word in
                           ['because', 'since', 'thus', 'therefore', 'consequently',
                            'as a result', 'this means'])
        has_nuance = any(word in content.lower() for word in
                        ['however', 'although', 'while', 'despite', 'nevertheless'])

        # Higher base score for foragers (refinement should be better)
        score = 0.45 + min(0.20, length / 300.0)

        # Bonuses for quality indicators
        if has_numbers:
            score += 0.12
        if has_specifics:
            score += 0.15
        if has_references:
            score += 0.12
        if has_reasoning:
            score += 0.10
        if has_nuance:
            score += 0.08

        # Smaller randomness (foragers more consistent)
        score += random.uniform(-0.03, 0.03)

        return max(0.0, min(1.0, score))

    def _make_prompt(self, signal: Signal) -> str:
        """Generate development prompt based on types.

        Priority order:
        1. task_frame directives (planner-set direction)
        2. task_config static templates
        3. Legacy inline prompts
        """
        # PRIORITY 1: Planner-set directives via TaskFrame
        frame = getattr(self.task_config, 'task_frame', None) if self.task_config else None
        if frame:
            if SignalType.is_support_type(self.output_type):
                directive = getattr(frame, 'forager_support_directive', '')
            elif SignalType.is_critique_type(self.output_type):
                directive = getattr(frame, 'forager_critique_directive', '')
            else:
                directive = getattr(frame, 'forager_support_directive', '')

            if directive:
                task_prompt = self.task_config.task_prompt if self.task_config else ""
                return (
                    f"Task: {task_prompt}\n\n"
                    f"Signal to develop:\n\"{signal.content}\"\n\n"
                    f"Your role: {directive}\n\n"
                    f"Your contribution (2-4 sentences):"
                )

        # PRIORITY 2: Static templates
        if self.task_config:
            # Choose template based on output type
            if SignalType.is_support_type(self.output_type):
                template = self.task_config.forager_evidence_prompt_template
            elif SignalType.is_critique_type(self.output_type):
                template = self.task_config.forager_critique_prompt_template
            else:
                # Fallback for other types - use evidence template
                template = self.task_config.forager_evidence_prompt_template

            return template.format(
                task_prompt=self.task_config.task_prompt,
                parent_content=signal.content,
                parent_type=signal.type.lower()
            )

        # LEGACY: Fallback to inline prompts for backward compatibility
        # Safeguard: check if legacy attributes are set
        if self.output_type is None or self.thesis is None:
            raise RuntimeError(
                f"Forager._make_prompt() called but legacy attributes not set. "
                f"This method is only for creative/debate mode. "
                f"output_type={self.output_type}, thesis={self.thesis}"
            )

        # Use universal type checking instead of hardcoded strings
        if SignalType.is_initial_type(self.output_type):
            return (f"You are a forager agent developing arguments about:\n"
                   f"\"{self.thesis}\"\n\n"
                   f"Initial signal: {signal.content}\n\n"
                   f"Task: Develop this into a clear, well-articulated claim. "
                   f"Add context, reasoning, or supporting details. Be specific "
                   f"and precise (2-3 sentences).\n\n"
                   f"Developed claim:")

        elif SignalType.is_support_type(self.output_type):
            return (f"You are a forager agent gathering evidence for this claim:\n"
                   f"\"{signal.content}\"\n\n"
                   f"Task: Provide specific evidence, data, or research findings "
                   f"that support this claim. Include numbers, sources, or study "
                   f"details where relevant. Be concrete and verifiable.\n\n"
                   f"Evidence:")

        elif SignalType.is_critique_type(self.output_type):
            # Include parent-claim context for better critiques
            parent_context = ""
            if signal.parent:
                parent_context = f"\nParent claim context: {signal.parent}\n"

            return (f"You are a forager agent analyzing this claim:\n"
                   f"\"{signal.content}\"{parent_context}\n"
                   f"Task: Identify and explain specific weaknesses, limitations, "
                   f"or counterarguments. Be analytical and constructive. Explain "
                   f"WHY this is a concern. Consider the broader context if provided.\n\n"
                   f"Critique:")

        else:
            return f"Develop this idea: {signal.content}\n\n"

    async def generate_defense(self, insight: Signal, objection: Signal,
                              signal_store: SignalStore, llm: SimpleLLM) -> Optional[str]:
        """Generate defense or acknowledge valid criticism.

        Args:
            insight: Original insight being challenged
            objection: Objection signal
            signal_store: Signal store for provenance lookup
            llm: Language model

        Returns:
            Defense/acknowledgment text or None
        """
        # Get original observations
        obs_ids = insight.metadata.get('observation_ids', [])
        observations = [signal_store.get_signal(oid) for oid in obs_ids if oid]
        observations = [obs for obs in observations if obs]  # Filter None

        observation_content = '\n'.join(f"- {obs.content}" for obs in observations)

        prompt = f"""You discovered this insight:
"{insight.content}"

Based on these observations:
{observation_content}

But an adversarial agent raised this objection:
"{objection.content}"

Task:
1. Is the objection valid? Does it identify a real weakness?
2. If valid, acknowledge and refine your insight to address it
3. If invalid, defend your insight with evidence from the observations
4. Be intellectually honest - admit if you were wrong

Response (2-3 sentences):"""

        # Read max_tokens from intake profile if available
        max_tokens = 220  # High-quality default
        if self.task_config and hasattr(self.task_config, 'intake_profile'):
            max_tokens = self.task_config.intake_profile.forager_tokens

        try:
            response = await llm.generate(prompt, max_tokens=max_tokens, temperature=0.7, use_cache=False)
            return response.strip() if response else None
        except Exception as e:
            logger.error(f"{self.agent_id} defense generation error: {e}", exc_info=True)
            return None

    def stop(self):
        """Stop the agent."""
        self.active = False

    # ========================================================================
    # STAGED EXECUTION METHODS (for parallel execution via StageCoordinator)
    # ========================================================================

    async def prepare_prompt(self, signal_store: SignalStore) -> Optional[Tuple[str, str, int, float]]:
        """Prepare prompt for staged execution (no LLM call).

        Returns:
            (agent_id, prompt, max_tokens, temperature) or None if nothing to do
        """
        # Check if should generate
        max_actions = getattr(self, 'max_actions', None)
        if not self.active or (max_actions is not None and self.actions_taken >= max_actions):
            return None

        # Check if input signals exist
        if not signal_store.has_signals(self.input_type):
            return None  # No input signals available

        # Sample parent signal
        input_signals = signal_store.sample_weighted(self.input_type, n=1)
        if not input_signals:
            return None

        parent_signal = input_signals[0]

        # Store parent for process_result
        self._current_parent = parent_signal

        # Build prompt using existing _make_prompt method
        prompt = self._make_prompt(parent_signal)

        # Get token allocation from config
        from ..core.config import TEMP_FORAGER
        max_tokens = 220  # High-quality default
        if self.task_config and hasattr(self.task_config, 'intake_profile'):
            max_tokens = self.task_config.intake_profile.forager_tokens

        return (self.agent_id, prompt, max_tokens, TEMP_FORAGER)

    async def process_result(self, result: str, signal_store: SignalStore) -> bool:
        """Process LLM result and deposit signal (staged execution).

        Args:
            result: Generated text from LLM
            signal_store: Signal store

        Returns:
            True if signal deposited, False otherwise
        """
        # Quality checks
        if not result or len(result.strip()) <= 20:
            return False

        clean_result = result.strip()

        # Get parent signal from prepare_prompt
        parent_signal = getattr(self, '_current_parent', None)
        if not parent_signal:
            logger.warning(f"{self.agent_id} no parent signal in process_result")
            return False

        # Optional verification (if enabled)
        if self.enable_verification and self.verifier:
            quality = self.verifier.verify(clean_result)
            if quality < self.verifier.min_quality_score:
                logger.debug(f"{self.agent_id} verification failed: quality={quality:.2f}")
                return False

        # Assess strength
        strength = self.assess_strength(clean_result)

        # Deposit with enhanced context (includes parent reference)
        signal_id = deposit_with_context(
            signal_store,
            signal_type=self.output_type,
            content=clean_result,
            strength=strength,
            depositor=self.agent_id,
            parent_signal=parent_signal
        )

        if signal_id:
            logger.info(f"{self.agent_id} deposited {signal_id} (strength={strength:.2f})")
            self.actions_taken += 1

            # Validate reference quality (optional logging)
            from ..core.signal_store import validate_reference_quality
            deposited_signal = signal_store.get_signal(signal_id)
            if deposited_signal:
                ref_quality = validate_reference_quality(deposited_signal, parent_signal)
                if ref_quality < 0.3:
                    logger.warning(f"{self.agent_id} weak parent reference: quality={ref_quality:.2f}")

            return True

        return False
